const CANDIDATE_KEYS = new Set(["recordId", "existingLabel", "proposedLabel", "score", "scoreBreakdown", "ruleDeltaIds", "evidence", "status", "verifier"]);
const DECISION_KEYS = new Set(["recordId", "decision", "reviewer", "reason"]); const UNDO_KEYS = new Set(["recordId", "reviewer", "reason"]); const DECISIONS = new Set(["approve", "reject", "escalate"]); const MAX_REASON_LENGTH = 1000; const LEDGERS = new WeakMap();
function fail(kind, message) { throw new Error(`Invalid ${kind}: ${message}`); }
function plain(value) { return Boolean(value) && typeof value === "object" && !Array.isArray(value) && Object.getPrototypeOf(value) === Object.prototype; }
function nonblank(value) { return typeof value === "string" && value.trim().length > 0; }
function assertObject(value, allowed, kind) { if (!plain(value) || Object.getOwnPropertySymbols(value).length > 0) fail(kind, "must be a plain object"); for (const key of Object.getOwnPropertyNames(value)) { const descriptor = Object.getOwnPropertyDescriptor(value, key); if (!descriptor?.enumerable || !Object.hasOwn(descriptor, "value") || !allowed.has(key)) fail(kind, `has unknown field ${key}`); } }
function safe(value, kind) { if (value === null || typeof value === "string" || typeof value === "boolean" || (typeof value === "number" && Number.isFinite(value))) return; if (Array.isArray(value)) { for (const item of value) safe(item, kind); return; } if (!plain(value) || Object.getOwnPropertySymbols(value).length > 0) fail(kind, "contains an unsafe value"); for (const key of Object.getOwnPropertyNames(value)) { const descriptor = Object.getOwnPropertyDescriptor(value, key); if (!descriptor?.enumerable || !Object.hasOwn(descriptor, "value") || ["__proto__", "constructor", "prototype"].includes(key)) fail(kind, `contains unsafe field ${key}`); safe(descriptor.value, kind); } }
function validateCandidate(candidate, { allowComputedStatus = false } = {}) { assertObject(candidate, CANDIDATE_KEYS, "candidate"); if (!nonblank(candidate.recordId) || !nonblank(candidate.proposedLabel)) fail("candidate", "recordId and proposedLabel are required"); if (Object.hasOwn(candidate, "existingLabel") && !nonblank(candidate.existingLabel)) fail("candidate", "existingLabel must be nonblank"); if (Object.hasOwn(candidate, "score") && !Number.isFinite(candidate.score)) fail("candidate", "score must be finite"); if (Object.hasOwn(candidate, "ruleDeltaIds") && (!Array.isArray(candidate.ruleDeltaIds) || !candidate.ruleDeltaIds.every(nonblank))) fail("candidate", "ruleDeltaIds must contain nonblank strings"); if (Object.hasOwn(candidate, "status") && (!allowComputedStatus ? candidate.status !== "pending" : !["pending", "approved", "rejected", "escalated"].includes(candidate.status))) fail("candidate", "status is not allowed"); safe(candidate, "candidate"); return structuredClone(candidate); }
function statusFor(decision) { return decision === null ? "pending" : { approve: "approved", reject: "rejected", escalate: "escalated" }[decision]; }
function validateHumanCommand(command, keys) { assertObject(command, keys, "decision"); if (!nonblank(command.reviewer)) fail("decision", "reviewer is required"); if (Object.hasOwn(command, "reason") && (!nonblank(command.reason) || command.reason.length > MAX_REASON_LENGTH)) fail("decision", "reason must be a nonblank string of at most 1000 characters"); }
export function createDecisionLedger(candidates, options = {}) {
  if (!Array.isArray(candidates)) fail("candidate list", "must be an array"); assertObject(options, new Set(["now"]), "decision options"); const now = options.now ?? (() => new Date().toISOString()); if (typeof now !== "function") fail("decision options", "now must be a function");
  const stored = candidates.map((candidate) => validateCandidate(candidate)); const stacks = new Map(); const events = []; for (const candidate of stored) { if (stacks.has(candidate.recordId)) fail("candidate", `duplicate recordId ${candidate.recordId}`); stacks.set(candidate.recordId, [{ decision: null, event: null }]); }
  function timestamp() { const value = now(); if (!nonblank(value)) fail("decision", "now must return a nonblank timestamp"); return value; }
  function currentCandidates() { return stored.map((candidate) => ({ ...structuredClone(candidate), status: statusFor(stacks.get(candidate.recordId).at(-1).decision) })); }
  function decide(command) { validateHumanCommand(command, DECISION_KEYS); if (!nonblank(command.recordId) || !stacks.has(command.recordId)) fail("decision", "recordId is unknown"); if (!DECISIONS.has(command.decision)) fail("decision", "decision is invalid"); const event = { type: "decision", sequence: events.length + 1, timestamp: timestamp(), recordId: command.recordId, decision: command.decision, reviewer: command.reviewer.trim(), reason: command.reason?.trim() ?? null }; events.push(event); stacks.get(command.recordId).push({ decision: command.decision, event }); return structuredClone(event); }
  function undo(command) { validateHumanCommand(command, UNDO_KEYS); if (!nonblank(command.recordId) || !stacks.has(command.recordId)) fail("decision", "recordId is unknown"); const stack = stacks.get(command.recordId); if (stack.length === 1) fail("decision", "record has no decision to undo"); const undone = stack.at(-1); const restored = stack.at(-2); const event = { type: "undo", sequence: events.length + 1, timestamp: timestamp(), recordId: command.recordId, reviewer: command.reviewer.trim(), reason: command.reason?.trim() ?? null, undoneSequence: undone.event.sequence, restoredDecision: restored.decision }; stack.pop(); events.push(event); return structuredClone(event); }
  const ledger = { decide, undo, candidates: currentCandidates, events: () => structuredClone(events) }; LEDGERS.set(ledger, { candidates: currentCandidates, events: () => structuredClone(events) }); return ledger;
}
function trustedExportState(ledger) { const state = LEDGERS.get(ledger); return state ? { candidates: state.candidates(), decisions: state.events() } : null; }
export const decisionInternals = { validateCandidate, statusFor, DECISIONS, trustedExportState };
